### ISSUE TITLE
Not working with Androidx

### ISSUE THREAD

**Issue by petr-stety-stetka** [tiper/MaterialSpinner#1]
With use androidx libraries spinner not working properly.
Can you fix it?

`implementation 'androidx.appcompat:appcompat:1.0.2'`

**Comment by tiper** [comment]
Hi @petr-stety-stetka, to use with AndroidX please ensure you have `android.useAndroidX=true` and `android.enableJetifier=true` on your `gradle.properties` and that your app theme extends a material component theme like `Theme.MaterialComponents.Light.DarkActionBar`.

If possible please also check if you are using `com.google.android.material:material:1.0.0`.

Cheers

**Comment by tiper** [comment]
In case you're using the `material:1.1.0-alphaXX` versions I've made changes to support them. Just update to version `1.0.1` and let me know if you still have issues.

**Comment by rajvimal** [comment]
Please help me to resolve this

        com.tiper.MaterialSpinner materialSpinner = new com.tiper.MaterialSpinner(new androidx.appcompat.view.ContextThemeWrapper(this, R.style.Widget_MaterialComponents_TextInputLayout_OutlinedBox));

    implementation 'com.google.android.material:material:1.2.0-alpha05'
    implementation 'androidx.appcompat:appcompat:1.0.2'

**Comment by tiper** [comment]
Hi @rajvimal please refer to #27
