### ISSUE TITLE
Issues at TextInputLayout

### ISSUE THREAD

**Issue by yoktavian** [tiper/MaterialSpinner#13]
Hi, are you checking for the compatible with new TextInputLayout?
I think you should replace from android.support.design.widget.TextInputLayout
 to com.google.android.material.textfield.TextInputLayout. Because it can't be compiled, I got error unresolved super types android.support.design.widget.TextInputLayout

Thx
Yuda Oktavian

**Comment by tiper** [comment]
Hi @yoktavian can you please check if you have `android.useAndroidX=true` and `android.enableJetifier=true` in your _gradle.properties_ file?

This has been tested with material 1.1.0-alpha10 without issues.

**Comment by YudaOktavian** [comment]
Oh, forgeting this step. Let me checking and recompiling the code. Thx 🙏

**Comment by yoktavian** [comment]
hi @tiper , after checking my `Gradle.properties` at my project, androidX and enableJetifier both of them is already have true value. But it's still not working, any solution?

**Comment by yoktavian** [comment]
<img width="1557" alt="Screen Shot 2019-10-03 at 11 00 31" src="https://user-images.githubusercontent.com/23457234/66098557-27c83780-e5cd-11e9-967d-e868453238e1.png">

**Comment by yoktavian** [comment]
case closed, missing `implementation 'com.android.support:design:28.0.0` at my Gradle. thx @tiper

**Comment by tiper** [comment]
Hi @yoktavian thanks for the feedback.
I'll update the README to try and clarify this widget dependencies.

Cheers.
