### ISSUE TITLE
spinner won't close in SDK 24

### ISSUE THREAD

**Issue by abehbatre** [tiper/MaterialSpinner#15]
hi there . i love this library , but i found bug in SDK 24, the spinner wont close after select item ..
i hope you fix it as soon  .. 

#androidx , #kotlin

**Comment by abehbatre** [comment]
close 

fix :

```XML
android:descendantFocusability="beforeDescendants"`
android:focusable="true"
android:focusableInTouchMode="true"
```

**Comment by tiper** [comment]
Dup: #4
