### ISSUE TITLE
Widget.MaterialComponents.TextInputLayout.OutlinedBox style not working in new materialCompontent version android

### ISSUE THREAD

**Issue by ABr751** [tiper/MaterialSpinner#16]
![Screenshot_1574154647](https://user-images.githubusercontent.com/32708867/69132844-da4f4d80-0ada-11ea-922d-5584182910c7.png)

The outlined box was appearing in 
    implementation 'com.google.android.material:material:1.0.0'

but when i updated that to

    implementation 'com.google.android.material:material:1.2.0-alpha01'

it's not working but it's appearing for TextInputLayout

**Comment by tiper** [comment]
Hi @ABr751 are you using the latest MaterialSpinner?

**Comment by tiper** [comment]
Hi @ABr751 any feedback on this?
Can you provide a demo project replicating the issue?

**Comment by ABr751** [comment]
I just did this with the latest version.It's working fine
