### ISSUE TITLE
Spinner Causes App Crash

### ISSUE THREAD

**Issue by tyrellshawn** [tiper/MaterialSpinner#18]
Error: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
        at com.tiper.MaterialSpinner$4$1.onFocusChange(MaterialSpinner.kt:281)
I have used the design library and android.enableJetifier and android.useAndroidX=true. My Implementation is in Java.

**Comment by tiper** [comment]
Hi @tyrellshawn thanks for the bug report.

The issue should be fixed on the next release.

**Comment by tiper** [comment]
Hi @tyrellshawn just release version 1.4.1 which should fix it.
