### ISSUE TITLE
Add the library Error

### ISSUE THREAD

**Issue by UmarRajput** [tiper/MaterialSpinner#2]
Library is not adding by using provided dependency:
implementation 'com.github.tiper:MaterialSpinner:latest.release.here'

Error:
Unable to resolve dependency for ':app@debug/compileClasspath': Could not find any version that matches com.github.tiper:MaterialSpinner:latest.release.here.

**Comment by tiper** [comment]
Hi @UmarRajput instead of using `latest.release.here` you should use the actual latest release reference which is `1.1.0`. In short `implementation 'com.github.tiper:MaterialSpinner:1.1.0`.
