### ISSUE TITLE
On selecting value in a spinner  the spinner is shown again and again..

### ISSUE THREAD

**Issue by ABr751** [tiper/MaterialSpinner#20]

**Comment by anees17861** [comment]
+1
I currently have two nougat phones and one android 10 phone in my reach. Android 10 seems to be working fine but nougat is giving this issue.
Tried with versions: 1.3.2, 1.3.3 and 1.4.1

**Comment by anees17861** [comment]
It seems their is already a fix provided in other issues which I didn't notice. Please close this and also provide a programmatic way of applying the solution.

**Comment by tiper** [comment]
Dup of #4
