### ISSUE TITLE
Selected item Text Color is showing Black

### ISSUE THREAD

**Issue by UmarRajput** [tiper/MaterialSpinner#3]
Hi @tiper Selected item Text Color is showing Black even that I set the android:textColor="@color/white" but its not working.

**Comment by tiper** [comment]
Hi @UmarRajput in order to theme the spinner you need to theme it just like you would be theming a TextInputLayout. Setting the parameters directly will not work. Please check the sample on how you can change the text color.

**Comment by UmarRajput** [comment]
Hi @tiper by theming a TextInputLayout its working. Thank you.
