### ISSUE TITLE
Allow choose "none"

### ISSUE THREAD

**Issue by petr-stety-stetka** [tiper/MaterialSpinner#5]
Hi,

Is some easy way, how select "none" in spinner?
Thanks!

Petr

**Comment by tiper** [comment]
Hi @petr-stety-stetka you can `setSelection(-1)` which will clear the value and invoke the `onNothingSelected` from the callback.

Take a look at the provided sample as example.

**Comment by petr-stety-stetka** [comment]
I think some better UI solution than separrate button for clearing, for example empty first item in dropdown.

**Comment by tiper** [comment]
You can easily achieve that behaviour by providing a _clear option_ as one of the possible selections from the spinner. On the callback `onItemSelected` if the position is the position of the _clear option_ you just call `setSelection(-1)` on the spinner.

For example:
### JAVA:
```java
if (position == 0) {
    spinner.setSelection(-1);
}
```
### Kotlin:
```kotlin
if (position == 0) {
    spinner.selection = -1
}
```
