### ISSUE TITLE
Cannot display more than 7 items

### ISSUE THREAD

**Issue by Marcosmaliki** [tiper/MaterialSpinner#7]
I've noticed that I can only display 7 items (in some cases). If the array is longer, only the last 7 elements are displayed.
Here's my test data
val data = arrayOf("me","him","them","hate","love","mine","yours", "ours","tada")
val aa = ArrayAdapter(this@EngineerHome, android.R.layout.simple_spinner_item, ins)
aa.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)

in this case, the first two elements are ignored

can you reproduce this on your end @tiper ?

**Comment by Marcosmaliki** [comment]
It only affects the dropdown mode. I've switched to dialog. Thank you for the awesome library.

**Comment by tiper** [comment]
Hi @Marcosmaliki when you open the spinner with a selection, the popup list will try to focus on the chosen element. Please check if scrolling the list will show the missing elements.
