### ISSUE TITLE
Not saving state on rotating screen

### ISSUE THREAD

**Issue by encore121** [tiper/MaterialSpinner#9]
First of all thanx for the greate control. 

When the screen is rotating the control not save the data

**Comment by tiper** [comment]
Hi @encore121 when you rotate a device the activity or fragment will be recreated. 
It's is good practice that the developer handles such situations.
Please take a look at `onSaveInstanceState` and `onRestoreInstanceState` callbacks.

For a more in depth understanding I would also recommend taking a look at the [Android lifecycle documentation](https://developer.android.com/guide/components/activities/activity-lifecycle)

**Comment by encore121** [comment]
Sure but the default spinner handle this by default only with his ID. But thanx any way.

**Comment by tiper** [comment]
Hi @encore121 seems I have misinterpreted the issue.

I'm reopening the issue until I properly fix it.

**Comment by tiper** [comment]
Hi @encore121 I just released version 1.3.3 that should fix the issue.
Please try it out and let me known if you still have any issues.

**Comment by encore121** [comment]
Hi @tiper sorry for the late in the answer. I try the version 1.3.3 and works equals the default spinner

Thanx

**Comment by tiper** [comment]
Thanks for the feedback.

Cheers
